### ISSUE TITLE
Prio 1 - Player Profile - Bases Functions

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#21]
As coaches we want to be able to create player profiles  for the active players so we can better develop each player. To do these we need a the be able to maintain various information directly on a player and have this accessible for the coaches. 

Base Information which should be stored on a player:
- [x] Leader Evalutaion - Level of player defined by coaching team
- [ ] Function Test - Passed / Failed
- [x] Positions - which the player can play -> created new issue for this: https://github.com/balzamas/waatea2/issues/55
- [x] Comments

Security:
- The secition of waatea needs to be secured, so only coaches using a login can access it. -> see https://github.com/balzamas/waatea2/issues/17
- [x] Each coach should have a owner user login not a shared one

Detail Field Requirements:

1. Leader Evalutation: These should be dropdown or other wise selecteble field with limited values based on [https://wiki.breu.tech/en/playerclassification](url)
2. Function Test - Passed or Failed bolean
3. Postions. multiple selection possible per player
4. Comments - Comments to player can be added. Information time comment was created an be whom is automatically added

**Comment by balzamas** [comment]
Comments without history/who wrote what, just one blob in RTF format

**Comment by balzamas** [comment]
@fabianbreu What exactly is the Function test?

**Comment by fabianbreu** [comment]
That is the fitness test sorry. The one with the excersises and the 12 min run
