### ISSUE TITLE
Prio 1 - Player Profile - Attendance Basic

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#22]
One big part of a player profile and also regarding the selection for games ist the attendance. Currently for each training Lou is creating a form. This should be changed to be done over waatea and also be added to the player profile

1. Training Attendance Form:
Admin: Any coach can just select a date for a training and activate it. Once activated player can submit. Once training starts no entries can be made by players any more. There coach / managers should be able to update the attendance of a player 
Players: Need to login to waatea and then can select the open training till start of the training
2. Player Profile change
- Field showing total trainings attendant
- Field showing how many of the last 4 trainings he attendet

**These is linked to Issue 24**.

**Comment by balzamas** [comment]
Current implementation:

Trainings can be created at 
https://new.waatea.vip/EFsaAh7KfgSNDTHc7gDyX3vd6cqAJgSv/waateaapp/training/

20 hours before and after the training, players can set if they are going/were at the training.

**Comment by balzamas** [comment]
I close the issue for the moment, we can make adjustments on how to present the data in a new issue after we gained some experience.
