### ISSUE TITLE
Prio 2 - Team Managemet - Basic - Core Team

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#23]
As coaches we need to be able to define the core teams based on the player profiles.

As coach we should be able to assign a player to one of the values
- 1st Team Core 
- 2n Team Core
- unassigned - Default or when above value gets deselected

Reporting:
As Coach a should be able to have a view were I can sie who is in which of the above set values

**Comment by balzamas** [comment]
Solved in v0.0.7
