### ISSUE TITLE
Prio 1 - Training Management - Basic

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#24]
As Coaches we need to be able to keep track of the trainings an what happend. 
So we need to be able to define trainings and add comments

A training should contain
- Date
- 1 - n field - Content. We should be able to add mutlle field were we can but in what was trained like : Defence, Attach, Fitness,... and comment field to each of the field to enter more details or thought aftere the training
- Posibility to add generall comments. 
- For all comment field it should be visible who / when added the comment

**These is linked to issue 22**

**Comment by balzamas** [comment]
The current training implementation seems to work for coaches, so we close this.
