### ISSUE TITLE
Player - Training Attandance

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#31]
When i login into waatea and klick on the training symbole the next open training should show up. I can than say yes or no. If I refresh it should show what i selecte

--> Currently it always shows ? even after i seleced one if go to other menu and come back

As Player I should also be able to select point which shows me for the past training what my attandance was. 

As Player I should not see the attendance of other players

**Comment by balzamas** [comment]
This is a bug. Players can set their attendance in their profile.
Details of other players will be only visible to coaches.

**Comment by balzamas** [comment]
Fix bug

As Player I should not see the attendance of other players -> part of https://github.com/balzamas/waatea2/issues/17

As Player I should also be able to select point which shows me for the past training what my attandance was. -> part of https://github.com/balzamas/waatea2/issues/2
