### ISSUE TITLE
Team Selection

### ISSUE THREAD

**Issue by fabianbreu** [balzamas/waatea2#78]
As coaches it would be great if we could do the selection preparation for games in waatea as we have all required information accessible.

Flow:

- For a game day it can be set which teams are playing
- For game day - team i can select players. 
- - Design would be great if the page would show tree sections. the normal menu left. in the middel i can select gameday and have to section below each other with each team is set to play. On the right side a list of players which set that they are available and maybe
- In the player list it should be shown there training attendance, if they are core players for one of both teams and the evaluation
- the team selection should be able to set player from 1 - 23. 
- a player can only be selected once per team. but he can be select in both team selections
- a player which is in both teams should be marked in both selections
- behind every selection a comment field should exist so we can add information
- The selection should only be visible the users in the coaching staff
- the coach can publish the selections. Once published the selection should be visible to everyone

**Comment by balzamas** [comment]
Phase 1:
- [ ] Line up tool, automatically show one or team team roosters
- [ ] Option to publish line ups
- [ ] Show line ups in games overview

Phase 2:
- [ ] Import line ups from old games

Phase 3:
- [ ] Add positions for players to database/UI (N:N)
- [ ] Edit positions in player details
- [ ] Add filtering in line up tool

Phase 4:
- [ ] Auto filter player positions when box in line up tool is selected (e.g. Pos 1 in lineup -> show all FR)

Phase 5:
- [ ] Comment for line up positions

**Comment by balzamas** [comment]
Filter by classification

**Comment by balzamas** [comment]
That's mostly implemented and in use, so we close this.
